
version: "2"
services:
  godaddy:
    image: "gcr.io/repcore-prod/godaddy:0"
    ports:
      - "21000:11000"
      - "21001:11001"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /creds/application_default_credentials.json
      ENVIRONMENT: local
    volumes:
      - ~/.config/gcloud:/creds
  godaddy-endpoints:
    image: "gcr.io/endpoints-release/endpoints-runtime:1"
    ports:
      - "21003:11003"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /creds/application_default_credentials.json
    command: ["-sgodaddy-api.vendasta-local.com", "-v[REPLACE THIS (INCLUDING THE []) WITH YOUR ENDPOINTS VERSION]", "-agrpc://godaddy:11000", "-p11003", "-zhealthz", "-k/creds/local-service-account.json"]
    depends_on:
      - "godaddy"
    volumes:
      - ./endpoints/local:/creds
