
version: "2"
services:
  godaddy:
    ports:
      - "21002:11002"
    expose:
      - "21002"
    entrypoint: dlv debug ../github.com/vendasta/LABS/godaddy/server -l 0.0.0.0:21002 --headless=true --log=true
    privileged: true
    security_opt:
      - seccomp:unconfined
